### ISSUE TITLE
Documentation for MSSQL is... well.... not very complete :-)

### ISSUE THREAD

**Issue by bovino** [SoftwareBrothers/adminjs-sequelizejs#69]
I tried to find a fully working (npm install + npm run start) example using MS SQL Server sample. With one entity only, no table relationship needed. 

Would it be possible to provide one please? Thanks for the good tool you provide.

**Comment by dziraf** [comment]
You can use official Sequelize examples on how to set it up with a specific database. This adapter should be database-agnostic and it's setup shouldn't differ if you're using MSSQL as long as you configure your models correctly in Sequelize.
