### ISSUE TITLE
Merge bugfix in v1.3.0-beta.5 to the rebranded version

### ISSUE THREAD

**Issue by feuye** [SoftwareBrothers/adminjs-sequelizejs#88]
The bug fix "use LIKE instead of ILIKE ([020cebd](https://github.com/SoftwareBrothers/adminjs-sequelizejs/releases/tag/v1.3.0-beta.5))" in v1.3.0-beta.5 hasn't been included in the rebranded version. resource.find method isn't available with AdminJS using Sequelize because of this issue.

Could we release a new version to include this change ?

**Comment by dziraf** [comment]
Beta branch was promoted in `2.1.0`
