### ISSUE TITLE
unordered database

### ISSUE THREAD

**Issue by ayuda-darma** [SoftwareBrothers/adminjs-sequelizejs#93]
I have a problem trying to populate the database because the order is reversed

i created the model Player_name, and Player_number
In mySQL database in order
1. Player_name
2. Player_number

but in adminpanel create, the order is reversed to
1. Player_number
2. Player_name

**Comment by dziraf** [comment]
You can change the order in two ways:
1. Define `editProperties`, `listProperties`, `showProperties`, `filterProperties`, e. g.: `editProperties: ['Player_name', 'Player_number']` - https://docs.adminjs.co/ResourceOptions.html#editProperties
2. Set `position` attribute for specific properties in resource options:
https://docs.adminjs.co/PropertyOptions.html#position
```
module.exports = {
  resource: Player,
  options: {
    properties: {
      Player_name: { position: 1 },
      Player_number: { position: 2 },
    }
  }
}
```

Let me know if you still have any troubles and I'll reopen.
